version: "3"
services:
  front:
    container_name: front
    build:
      context: ./front
    volumes:
      - './front:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
